version: "2.19.1"
services:
  osu.mysql.dl:
    container_name: opal.mysql.dl
    extends:
      file: osu-data-docker/docker-compose.yml
      service: osu.mysql.dl

  osu.mysql:
    container_name: opal.mysql
    extends:
      file: osu-data-docker/docker-compose.yml
      service: osu.mysql

  osu.files:
    container_name: opal.files
    extends:
      file: osu-data-docker/docker-compose.yml
      service: osu.files
    volumes:
      - ./opal.files:/osu.files

  opal.compute_visual_complexity:
    container_name: opal.compute_visual_complexity
    image: opal.compute_visual_complexity
    depends_on:
      - osu.mysql
    build:
      context: .
      dockerfile: ./compute_visual_complexity.Dockerfile
    volumes:
      - ./opal.files:/opal.files

volumes:
  osu.mysql.vol:
  osu.mysql.dl.vol:
  osu.files.vol:
