version: "2.20.2"
include:
  - osu-data-docker/.docker-compose.yml

services:
  1.preprocess:
    image: mysql
    depends_on:
      osu.mysql:
        condition: service_healthy
      osu.files:
        condition: service_healthy
    environment:
      - SR_MIN=${SR_MIN}
      - SR_MAX=${SR_MAX}
      - ACC_MIN=${ACC_MIN}
      - ACC_MAX=${ACC_MAX}
      - MIN_SCORES_PER_MID=${MIN_SCORES_PER_MID}
      - MIN_SCORES_PER_UID=${MIN_SCORES_PER_UID}
    working_dir: /src/preprocess
    volumes:
      - ../:/src/
    entrypoint: /src/preprocess/1_entrypoint.sh

  2.svness:
    image: python:3.9
    depends_on:
      1.preprocess:
        condition: service_completed_successfully
    environment:
      - FILES_DIR=${FILES_DIR}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    build:
      context: .
      dockerfile: 2_svness.Dockerfile
    working_dir: /src/opal/
    volumes:
      - ../:/src/
      - /var/lib/osu/osu.files/:/var/lib/osu/osu.files/
    entrypoint: /src/preprocess/2_entrypoint.sh

  3.preprocess:
    image: mysql
    depends_on:
      2.svness:
        condition: service_completed_successfully
    environment:
      - MAX_SVNESS=${MAX_SVNESS}
    working_dir: /src/preprocess
    volumes:
      - ../:/src/
    entrypoint: /src/preprocess/3_entrypoint.sh

  4.export:
    image: mysql
    depends_on:
      3.preprocess:
        condition: service_completed_successfully
    environment:
      - DATASET_NAME=${DATASET_NAME}
    working_dir: /src/preprocess/
    volumes:
      - ../:/src/
    entrypoint: /src/preprocess/4_entrypoint.sh
