version: "2.19.1"
services:
  pytorch.lightning.eval:
    image: pytorch.lightning.evaluate
    stdin_open: true
    container_name: pytorch.lightning.evaluate
    working_dir: /src
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - DATASET_NAME=${DATASET_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/src/
    entrypoint: /entrypoint.sh
