# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Neu MF Model

on: [ pull_request ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8" ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Add data_ppy_sh_to_csv init
        run: |
          touch opal/data_ppy_sh_to_csv/__init__.py

      - name: Check dirs
        run: |
          ls
      - name: Check dirs
        run: |
          ls opal/data_ppy_sh_to_csv
        

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt
          pip install -r opal/data_ppy_sh_to_csv/requirements.txt


      - name: Test with pytest
        run: |
          pytest tests/score_tests/
