# This workflow will build opal, install its build, then runs the tests with pytest.


name: Test Model Building Inference

on: [ pull_request ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Build opal with Docker
        working-directory: src/build/
        run: |
          export MODEL_NAME=V4 
          docker compose up --build

      - name: Install opal build
        working-directory: src/
        run: |
          python -m pip install dist/*.whl

      - name: Remove local opal
        run: |
          rm -rf src/opal/

      - name: Test with pytest
        run: |
          pytest tests/
