version: "2.19.1"
services:
  pytorch.lightning:
    image: pytorch.lightning
    stdin_open: true
    container_name: pytorch.lightning
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app/
    entrypoint: python3 -m opal.train
