version: "2.19.1"
services:
  pytorch.lightning:
    image: pytorch.lightning
    stdin_open: true
    container_name: pytorch.lightning
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../datasets:/var/lib/opal/datasets
      - ../lightning_logs/:/var/lib/opal/lightning_logs
    ports:
      - 6006:6006 # Tensorboard Port
    entrypoint: python3 -m opal.train
