version: "2.19.1"
services:
  pytorch.lightning:
    image: pytorch.lightning
    stdin_open: true
    container_name: pytorch.lightning
    working_dir: /src
    environment:
      - DATASET_NAME=${DATASET_NAME}
      - MODEL_NAME=${MODEL_NAME}
      - ENV_FILE_PATH=${ENV_FILE_PATH}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/src/
    entrypoint: /entrypoint.sh
