version: "2.19.1"
services:
  pytorch.lightning:
    image: pytorch.lightning
    stdin_open: true
    container_name: pytorch.lightning
    working_dir: /src
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/src/
    entrypoint: /entrypoint.sh ${PIPELINE_RUN_CACHE}
